CREATE TABLE items (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  genre VARCHAR(50) NOT NULL,
  author VARCHAR(50) NOT NULL,
  source VARCHAR(50) NOT NULL,
  label VARCHAR(50) NOT NULL,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  FOREIGN KEY (labels_id) REFERENCES labels(id)
);

CREATE TABLE books (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  publisher VARCHAR(50) NOT NULL,
  cover_state VARCHAR(50) NOT NULL,
  FOREIGN KEY (id) REFERENCES items(id)
);

CREATE TABLE labels (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL
);
